---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Copy backend files"
  become: yes
  unarchive:
    src:  /root/project/backend.tar.gz
    dest: ~/
    owner: ubuntu

- name: Executing node
  shell: |
    cd ~/backend
    pm2 start --name backend npm -- start
    pm2 ls